services:
  parser:
    build: .
    stdin_open: true
    tty: true
    command: ["sh"]
    volumes:
      - type: bind
        source: ./input
        target: /mnt/input
        read_only: true
      - type: bind
        source: ./output
        target: /mnt/output
        read_only: false

